//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _44Resources.WCF.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_BA_BankDetail> tbl_BA_BankDetail { get; set; }
        public virtual DbSet<tblBusinessAssociate> tblBusinessAssociates { get; set; }
    
        public virtual ObjectResult<usp_BA_Signup_Result> usp_BA_Signup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BA_Signup_Result>("usp_BA_Signup");
        }
    }
}
