//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _44Resources.WCF.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BA_BankDetail
    {
        public int Id { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string ConfirmAccountNo { get; set; }
        public string IFSCcode { get; set; }
        public string BankAddress { get; set; }
        public string BankBranch { get; set; }
    }
}
